### PR TITLE
Add support for MongoDB text index creation

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Re-implement https://github.com/Meteor-Community-Packages/meteor-collection2/pull/250 by @kdorsel
And update dependencies & test platform (currently failing)

### CODE REVIEW

**Comment by jankapunkt** [comment]
@StorytellerCZ any update on this? It's still in draft stage.

**Comment by StorytellerCZ** [comment]
@jankapunkt Need to take another look and test this.

**Comment by jankapunkt** [comment]
@StorytellerCZ can I test this somehow? Simply clone and run?

**Comment by StorytellerCZ** [comment]
@jankapunkt yes, that should be it. I haven't touched this in a while and originally copied it from the meteor-collection2 repo with updates to the current version.

**Pull request closed without merging**
