### PR TITLE
Reindex on change of `unique` or `sparse`

### LINKED ISSUE #19: Doesn't re-create the index if an index-setting (like `unique`) changes
First I created a property on an object and also created a unique index for it by adding `{ unique: true }`. After some time of development I had to remove it, but it still remains in MongoDB. After reading the manual, I knew that it works when adding `{ index: false }` to the configuration, but this doesn't help on a property where I want an index, but not unique.

### PR DESCRIPTION
**Pull request by SimonSimCity**
This fixes #19 and requires #20 to be merged first.
  
The only downside is, that this script doesn't handle a changed definition from `{ name: 'foo', unique: true }` to `{ name: 'foo', unique: false }`. It will not delete the unique index of this property, neither will it re-create the index without uniqueness required.

Should I change the cod so it removes such an index?

### CODE REVIEW

**Comment by aldeed** [comment]
@SimonSimCity This is good and can be merged after a few things.

1. Can you rebase on master now that I merged your other PR?
2. Can you add a few tests to show that this works in different circumstances? I do not think this will work if you have `unique: true` without `index: true` and then you remove `unique` or set to `false` because it is wrapped in `if ('index' in definition || definition.unique === true)`. The conditional logic will probably have to be tweaked a bit.
3. As long as you're going to do this for `unique` and `sparse`, might as well make it work when you remove `index` without setting it to `false`, right? The correct approach to make it all work might be to loop through the existing indices before the schema loop, and if any don't match their schema, drop them. Then do the current loop through the schema to re-add them.

**Comment by aldeed** [comment]
We would also need to be careful that we don't drop existing indices added outside of this package. When adding them to `existingIndexes`, you should check first to make sure that `index.name` starts with `c2_`. Add a test for this, too.

**Comment by SimonSimCity** [comment]
Sorry for it taking soo long time for me to get back to you here ...

I've now rebased it on `master` and tried to run the tests, but wasn't able to. The command, stated in the `README.md` (`npm test:watch` or `npm test`) resulted in an error and calling `meteor test-packages ./package/indexing/` - which was my next guess, since this is a meteor package - left me without any tests. Can you please help me in getting this going?

**Comment by SimonSimCity** [comment]
@aldeed could you please help me to run the tests?

**Pull request closed without merging**
